name: Terraform CICD Pipeline - ECS PROJECT

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Pipeline
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'eu-west-1'
      TF_VERSION: '1.4.0'
      TFLINT_VERSION: 'v0.46.1'

    steps:
      - name: 'Checkout GitHub repository'
        uses: actions/checkout@v3

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: 'Set up TFLint'
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: ${{ env.TFLINT_VERSION }}

      - name: 'Terraform Init'
        run: terraform -chdir=terraform init

      - name: 'Terraform Format'
        run: terraform -chdir=terraform fmt

      - name: 'Terraform Validate'
        run: terraform -chdir=terraform validate

      - name: 'TFLint'
        run: |
          tflint --init
          tflint

      - name: 'Terraform Plan'
        run: terraform -chdir=terraform plan -out=tfplan

      - name: 'Terraform Apply'
        run: terraform -chdir=terraform apply -auto-approve tfplan
